name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Використання Windows замість Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true

    - name: Build Project
      run: |
        mkdir -p build
        g++ -o build/client lib/client/main.cpp -std=c++17

    - name: Test Application
      run: |
        ./build/client
