name: Build and Test

on:
  push:
    branches:
      - main
      - feature/develop/task2
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install C++ Compiler
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc

    - name: Build Project
      run: |
        mkdir -p build
        g++ -o build/client lib/client/main.cpp -std=c++17

    - name: Test Application
      run: |
        ./build/client
